[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odooloyaltycard
db_password = odooloyaltycard
db_name = odooloyaltycard
dbfilter = ^odooloyaltycard$
list_db = False
admin_passwd = admin
